name: Zola build

on:
  push:
    branches:
    - develop
    - stage

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trottomv/zola:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      options: --volume ${{ github.workspace }}:/app
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check
      run: zola --config config.${{ github.ref_name }}.toml check
    - name: Build
      run: zola --config config.${{ github.ref_name }}.toml build --force --output-dir docs
    - name: Push build
      run: |
        git config --global --add safe.directory "*"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global github.token ${{ secrets.GITHUB_TOKEN }}
        git commit -a -m "Build ${{ github.ref_name }}" || true
        git push origin ${{ github.ref_name }}
