name: Zola build

on:
  push:
    branches:
      - develop
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage
        uses: actions/checkout@v3.0.0
      - name: Setup alpine
        uses: jirutka/setup-alpine@v1
        with:
          extra-repositories: |
            http://dl-cdn.alpinelinux.org/alpine/edge/community/
          packages: zola
          options: --volume ${{ github.workspace }}:/workdir --workdir /workdir
      - name: Check
        run: zola --config config.${{ github.ref_name }}.toml check
        shell: alpine.sh {0}
      - name: Build
        run: yes | zola --config config.${{ github.ref_name }}.toml build --force --output-dir docs || true
        shell: alpine.sh {0}
      - name: Commit build
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Build ${{ github.ref_name }}"
      - name: Push build
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
