name: Zola check

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/trottomv/zola:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}
      options: --volume ${{ github.workspace }}:/app
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Check develop
        run: zola --config config.develop.toml check
      - name: Check stage
        run: zola --config config.stage.toml check
