name: Zola on GitHub Pages

on:
  push:
    branches:
      - stage

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout stage
        uses: actions/checkout@v3.0.0
      - name: Build
        uses: jirutka/setup-alpine@v1
        with:
          extra-repositories: |
            http://dl-cdn.alpinelinux.org/alpine/edge/community/
          packages: zola
          options: --volume ${{ github.workspace }}:/workdir --workdir /workdir
          run: zola build --output-dir docs
